apiVersion: apps/v1
kind: Deployment
metadata:
  name: cap-deploy
  labels:
    app: capstone-app
    
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
        
    spec:
      containers:
      - name: capstone-website
        image: adenicole/capstone
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-LB
  labels:
    app: capstone
    
spec:
  selector:
    app: capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  
